### ISSUE TITLE
Low accuracy on audio recognition "yes/no" on 'micro_speech' example.

### ISSUE THREAD

**Issue by misterb0407** [espressif/tflite-micro-esp-examples#47]
I tried the example on 'micro_speech' folder but it coud not detect when I said "yes" to the microphone.

Setup:
board: ESP-EYE
ESP-IDF release version : v 5.0.1

Steps:
1. cd to 'examples/micro_speech'
2. issue commands:
```
$ idf.py set-target esp32
$ idf.py build
$ idf.py flash <usb_port>
$ idf.py monitor <usb_port>
```
3. If I don't speak anything, the console just print output either 'no' or 'unknown:
```
Heard unknown (203) @2223400ms
Heard no (211) @2226900ms
Heard no (205) @2236700ms
Heard unknown (210) @2245000ms
Heard unknown (206) @2253800ms
Heard unknown (201) @2262500ms
Heard unknown (203) @2266400ms
Heard no (211) @2268200ms
```

4. The same thing happen when I said "yes", the console just output either "no" or "unknown" like in 3).
5. Occasionally it detect "yes" correctly if I speak "yes" repeatedly close to the microphone.

Any pointer what might be the issue?

**Comment by vikramdattu** [comment]
@misterb0407 as I have answered here: https://github.com/espressif/tflite-micro-esp-examples/issues/52#issuecomment-1590495909,
The model from the example seem to be working as expected. Can you please check if mic of your ESP-EYE is recording distorted audio maybe because it has dirt on it or some other issues?
Closing this issue, since the discussion is already going on other thread and the model seems to give decent results as in the above linked comment.
